# Generated by Django 5.0.4 on 2024-04-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_daycare', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Babe',
            new_name='Baby',
        ),
    ]
