# Generated by Django 5.0.4 on 2024-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_daycare', '0002_rename_babe_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='b_name',
            new_name='b_firstname',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='timein',
            new_name='timeIn',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='timeout',
            new_name='timeOut',
        ),
        migrations.AddField(
            model_name='baby',
            name='b_lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
