# Generated by Django 5.0.4 on 2024-04-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_daycare', '0005_rename_s_name_sitter_s_nin_remove_payment_c_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='s_nextofkin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
