# Generated by Django 5.0.4 on 2024-04-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_daycare', '0006_sitter_s_nextofkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='c_stay',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paye',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='paye',
        ),
        migrations.DeleteModel(
            name='Sitter',
        ),
        migrations.DeleteModel(
            name='Categorystay',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Baby',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
    ]
